### ISSUE TITLE
Smooth Scroll issue on Safari (Mac OS)

### ISSUE THREAD

**Issue by SebastienGicquel** [erfanmola/ScrollSpy.js#1]
Hello,

I've tested `ScrollSpy.js` and I've noticed that there is no scroll on safari (it works on Chrome and Firefox). On Safari, if we click on a link inside `scrollspy-indicator`, the page goes directly to anchor without scroll.

Sébastien

**Comment by erfanmola** [comment]
The code used for smooth-scrolling in VanillaJS is : 

```
window.scrollTo({
            top: offset,
            behavior: 'smooth'
});
```

I have not tested this on Safari, you can test the code itself to see if it works or not, then inform on this topic
